# Literature Review 

This chapter contains a summary of the context in which your research is set.

Imagine you are writing for your fellow PhD students. Topics that are well-known to them do not have to be included here. But things that they may not know about should be included.

Resist the temptation to discuss everything you've read in the last few years. And you are not writing a textbook either. This chapter is meant to provide the background necessary to understand the material in subsequent chapters. Stick to that.

You will need to organize the literature review around themes, and within each theme provide a story explaining the development of ideas to date. In each theme, you should get to the point where your ideas will fit in. But leave your ideas to later chapters. This way it is clear what has been done beforehand, and what new contributions you are making to the research field.

All citations should be done using markdown notation as shown below. This way, your bibliography will be compiled automatically and correctly.

## Various lit 


One time @achenBlindRetrospectionElectoral2002 said something about sharks and then @fowlerSharkAttacksInfluence2018 and thus the great shark debate started 
