project:
  type: book

book:
  search: false
  chapters:
    - acknowledgment.qmd
    - abr.qmd
    - index.qmd
    - "01-chap1.qmd"
    - "02-chap2.qmd"

fig-height: 3.8
fig-width: 6.3
execute:
  freeze: TRUE
  echo: false
format:
  gsuthesis-pdf:
    keywords: "These, Are, Tests"
    toc-title: "Table of Contents"
    biblatex: true
    bibliography: ref.bib
    biblio-style: apa
    chair: "Ellen Ripley"
    memberone: "Bruce Banner"
    membertwo: "Indiana Jones"
    month: "May"
    uppername: "JOSH ALLEN"
    normname: "Josh Allen"
    title: "Testing the Effect of something on something else"
    year: 2022
